language: node_js
node_js:
  - "4.1"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm install -g gulp
script: gulp test && gulp clean build
deploy:
  provider: gae
  keyfile: .amp-by-example.json.enc
  project: amp-by-example
  default: true
  skip_cleanup: true
