language: node_js
node_js:
- '4.1'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install -g gulp
script: gulp test && gulp clean build
deploy:
  provider: gae
  keyfile: client-secret.json
  project: amp-by-example
  default: true
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_8592b1f8cf3c_key -iv $encrypted_8592b1f8cf3c_iv
  -in client-secret.json.enc -out client-secret.json -d
