language: node_js
node_js:
- '4.1'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install -g gulp
script: gulp test && gulp clean build
before_install:
  - openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar
deploy:
  provider: gae
  keyfile: client-secret.json
  project: amp-by-example
  default: true
  skip_cleanup: true
