sudo: false
language: node_js
node_js:
- '4.1'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install -g gulp
script: gulp test && gulp clean build
before_install:
- openssl aes-256-cbc -K $encrypted_8592b1f8cf3c_key -iv $encrypted_8592b1f8cf3c_iv
  -in client-secret.json.enc -out client-secret.json -d
after_success:
- test $TRAVIS_PULL_REQUEST == "true" && exit 0
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- curl go_appengine_sdk_linux_amd64-1.9.33.zip > go_appengine_sdk_linux_amd64.zip
- unzip go_appengine_sdk_linux_amd64.zip
- gcloud auth activate-service-account --key-file client-secret.json
- go_appengine/appcfg.py update . --skip_sdk_update_check --oauth2_access_token=$(gcloud auth print-access-token) -A amp-by-example -V 1
