application: amp-by-example
version: 1
runtime: go
api_version: go1

handlers:

- url: /
  mime_type: text/html
  static_files: dist/index.html
  upload: noop

- url: /(.*\.html)
  mime_type: text/html
  static_files: dist/\1
  upload: dist/(.*\.html)

# favicons file
- url: /favicons/(.*\.(bmp|gif|ico|jpeg|jpg|png|xml|json|webapp))
  static_files: dist/favicons/\1
  upload: dist/favicons/(.*\.(bmp|gif|ico|jpeg|jpg|png|xml|json|webapp))

# license file
- url: /(.*\.txt)
  mime_type: text/plain
  static_files: dist/\1
  upload: dist/(.*\.txt)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: dist/\1
  upload: dist/img/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /.*
  script: _go_app

skip_files:
- node_modules
- spec
- lib
- src
- tasks
